# Generated by Django 2.2 on 2019-07-11 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('Basic', 'basic'), ('Top', 'top'), ('Destaque', 'destak'), ('Diamond', 'diam')], default='Basic', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('valide_time', models.CharField(choices=[('30', '30 dias'), ('15', '15 dias'), ('7', '7 dias')], default='15', max_length=30)),
                ('beneficios', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField(default=3, verbose_name=((0, 'Diamond'), (1, 'Destak'), (2, 'Top'), (3, 'Basic')))),
                ('code', models.CharField(help_text='codigo de validação', max_length=100, unique=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assina.Membership')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eros.Perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
