# Generated by Django 2.2 on 2019-07-11 05:25

import apps.eros.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Denunciar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_id', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
            },
        ),
        migrations.CreateModel(
            name='NewsLettersAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NewsUser',
                'verbose_name_plural': 'NewsUsers',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=50)),
                ('idade', models.IntegerField(blank=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('peso', models.IntegerField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('capa', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.eros.models.path_perfil)),
                ('is_vip', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
                ('is_working', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eros.City')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='account.Agente')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Brasil', max_length=100)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('planoId', models.IntegerField()),
                ('transactionCode', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, unique=True)),
                ('video', models.FileField(blank=True, upload_to=apps.eros.models.video_path_album)),
                ('is_public', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='date added')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eros.Perfil')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-date_added'],
                'get_latest_by': 'date_added',
            },
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caches_1h', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('caches_2h', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('caches_3h', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('caches_4h', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('caches_pernoite_dia_util', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('caches_sexta_noite', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('caches_fim_semana_dia', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('caches_sabado_noite', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='eros.Perfil')),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
            },
        ),
        migrations.CreateModel(
            name='Service_especial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beijo_negro', models.BooleanField(default=False)),
                ('chuva_dourada', models.BooleanField(default=False)),
                ('fetichismo', models.BooleanField(default=False)),
                ('garganta_profunda', models.BooleanField(default=False)),
                ('sado_duro', models.BooleanField(default=False)),
                ('sado_suave', models.BooleanField(default=False)),
                ('squirting', models.BooleanField(default=False)),
                ('strap_on', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especiais', to='eros.Perfil')),
            ],
            options={
                'verbose_name': 'Service Especial',
                'verbose_name_plural': 'Service Especiais',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beijo_na_boca', models.BooleanField(default=False)),
                ('duplas', models.BooleanField(default=False)),
                ('ejacula_corpo', models.BooleanField(default=False)),
                ('fan_disfarces', models.BooleanField(default=False)),
                ('massagem_erotica', models.BooleanField(default=False)),
                ('namoradinha', models.BooleanField(default=False)),
                ('pse', models.BooleanField(default=False)),
                ('sexo_anal', models.BooleanField(default=False)),
                ('sexo_oral_com_cam', models.BooleanField(default=False)),
                ('sexo_oral_sem_cam', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='eros.Perfil')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='PerfilViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='eros.Perfil')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PerfilNumberClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, null=True)),
                ('clicked', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klics', to='eros.Perfil')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.BooleanField(default=False)),
                ('motel', models.BooleanField(default=False)),
                ('local_proprio', models.BooleanField(default=False)),
                ('sobre_convite', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='eros.Perfil')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, unique=True)),
                ('image_erociti', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.eros.models.image_path_album_erociti)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date added')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='eros.Perfil')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='DadosPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('cabelo', models.CharField(blank=True, max_length=50)),
                ('etnia', models.CharField(blank=True, max_length=50)),
                ('seios', models.CharField(blank=True, max_length=50)),
                ('men', models.BooleanField(default=True)),
                ('women', models.BooleanField(default=False)),
                ('couple', models.BooleanField(default=False)),
                ('dote', models.IntegerField(blank=True)),
                ('tipo', models.CharField(blank=True, max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='eros.Perfil')),
            ],
            options={
                'verbose_name': 'Dados perfil',
                'verbose_name_plural': 'Dados perfis',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='eros.State'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created', models.DateField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='eros.Perfil')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'albuns',
                'ordering': ['-created'],
            },
        ),
    ]
